# numpy
* https://numpy.org/numpy.tutorials/
* numpy: Nemerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 파이썬의 list와의 차이는 자료형이 1가지만 들어간다.


# 차원
* 0차원 = 점 . 스칼라 a = 10
* 1차원 = 선 -------- 벡터, 배열, list, tuple .[1,2,3,4].
    * 벡터는 방향을 가진 데이터
* 2차원 = 면, 가로, 세로, DB 테이블, Dataframe, matrix
* 3차원 = 입체, 가로, 세로, 높이, 정육면체
* 4차원 = 3차원 요소가 3개 이상
* 5차원 = 4차원 요소가 2개 이상

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [4]:
s = 10 # 스칼라.. 데이터 한 개만 있는 것

* 차원을 출력하는 메서드 .ndim,
* 차원의 형태를 출력하는 메서드 .shape

In [6]:
# ndarray는 벡터이므로 1차원
a.ndim

1

In [8]:
# 방향이 없는 벡터
a.shape

(5,)

In [14]:
# 2차원 데이터
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
# 1차원이 두 개 있으니까 2
c.ndim

2

In [13]:
c.shape
#2는 행 / 5는 열

(2, 5)

In [16]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [19]:
d.ndim

3

In [21]:
d.shape

(2, 2, 5)

In [27]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [28]:
e.shape

(1, 3, 2, 5)

In [31]:
# 5차원 데이터
f = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
             [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
             [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
             [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])
f

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [33]:
# 세로로 방향을 가진 행벡터
a2 = np.array([[1], [2], [3], [4], [5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

# 넘파이를 사용하는 이유
* 행렬 연산이 쉽고 빠르기 때문에

In [35]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)

15


In [37]:
scalar + 10

25

In [40]:
# 1차원 데이터 벡터의 연산
b1 = [1,2,3,4,5]
# 리스트의 요소에 10을 곱한 후 다시 리스트로 만드세요
result = []
for num in b1:
    result.append(num*10)
result

[10, 20, 30, 40, 50]

In [43]:
result2 = [num * 10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [46]:
second = np.array([[1,2,3], [1,2,3]])
print(second, second.ndim, second.shape)

[[1 2 3]
 [1 2 3]] 2 (2, 3)


In [51]:
result = []
for num in second:
    for number in num:
        result.append(number * 10)
result

[np.int64(10),
 np.int64(20),
 np.int64(30),
 np.int64(10),
 np.int64(20),
 np.int64(30)]

In [53]:
# 3차원 데이터의 요소에 10 곱하기
third = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
print(third, third.ndim, third.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 3 (2, 2, 3)


In [63]:
result = []
for num1 in third:
    num1_result = []
#     print(num1, end="\n\n")
    for num2 in num1:
#         print(num2)
        num2_result = []
        for num3 in num2:
            num2_result.append(num3 * 10)
        num1_result.append(num2_result)
    result.append(num1_result)
result = np.array(result)

In [64]:
result

array([[[10, 20, 30],
        [10, 20, 30]],

       [[10, 20, 30],
        [10, 20, 30]]])

In [66]:
result.shape

(2, 2, 3)

In [69]:
# 4차원 데이터에 10 곱하기

forth = np.array([[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                  [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]])
forth

array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]])

In [70]:
forth * 10

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]]])

In [72]:
# 5차원 데이터에 10 곱하기

fifth = np.array([[[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                  [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]],
                 [[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                  [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]]])
print(fifth.ndim, fifth.shape)

5 (2, 2, 2, 2, 3)


In [74]:
fifth * 10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

# numpy에서 자주 사용하는 메서드
* .ndim: 몇 차원인지 보는 것
* .shape: 몇 차원, 몇 행, 몇 열로 되어 있는지 구조 확인
* .size: 배열 안에 있는 요소의 총 개수가 몇 개인지
* .dtype: 데이터 타입이 무엇인지

In [75]:
fifth.ndim

5

In [77]:
fifth.shape
# 2행 3열짜리 데이터가 2개 모여있고, 2개 모여있고 2개 모임

(2, 2, 2, 2, 3)

In [78]:
fifth.size

48

In [79]:
fifth.dtype

dtype('int64')

In [81]:
fifth2 = fifth/2
fifth2

array([[[[[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]],

         [[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]]],


        [[[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]],

         [[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]]]],



       [[[[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]],

         [[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]]],


        [[[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]],

         [[0.5, 1. , 1.5],
          [0.5, 1. , 1.5]]]]])

# ndarray 만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [83]:
print(*[1,2,3,4,5])

1 2 3 4 5


In [84]:
e = np.array((1,2,3,4,5))
e

array([1, 2, 3, 4, 5])

In [87]:
e2 = np.array((1, 2, 3.14, 4, 5))
print(e2)
e2.dtype



[1.   2.   3.14 4.   5.  ]


dtype('float64')

In [89]:
e3 = np.array((True, 1, 2, 3.14, "4", 5))
print(e3)
e3.dtype



['True' '1' '2' '3.14' '4' '5']


dtype('<U32')

* np.arange(시작, 끝, step)

In [90]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [92]:
a2 = np.arange(11, 1, -3)
a2

array([11,  8,  5,  2])

In [93]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [97]:
# .reshape(행과 열) 벡터를 원하는 크기의 matrix 또는  다차원 배열로 변환해주는 함수

print(a3.ndim)
print(a3.shape)
a4 = a3.reshape(20, 5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [98]:
# flatten(): 다차원 배열을 1차원으로 펼쳐줌


In [100]:
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [102]:
a7.ndim

4

In [104]:
a7.shape

(3, 2, 2, 2)

In [106]:
a7.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [107]:
# np.flip() 행렬의 순서를 뒤집을 때
np.flip(a73)

NameError: name 'a73' is not defined

In [110]:
#linspace(시작, 끝, 구간 수): 정해진 숫자 범위 안에서 균등하게 구간 나누기
    
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [112]:
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [ ]:
print(sorted(f))

In [113]:
f = f.reshape(2,5)
f.sort()
f

NameError: name 'f' is not defined

In [114]:
# argsort() 자료 중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
g = np.array([5, 0.5, -7, 42, 10, 0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [ ]:
# 2, 5, 1, 0, 4, 3

In [117]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [119]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])